CREATE DATABASE MinhaAgencia;
use MinhaAgencia;


CREATE TABLE Cliente (
IDCliente VARCHAR(10) PRIMARY KEY,
Nome VARCHAR(10) NOT NULL,
Endereco VARCHAR(10) NOT NULL,
Telefone VARCHAR(10) NOT NULL,
Email VARCHAR(10),
Sobrenome VARCHAR(10) NOT NULL,
IDCadastro VARCHAR(10)
);

CREATE TABLE Cadastro (
IDCadastro VARCHAR(10) PRIMARY KEY,
InformacaoCliente VARCHAR(50),
HistoricoDeCompra VARCHAR(50)
);

CREATE TABLE Destino (
IDDestino VARCHAR(10) PRIMARY KEY,
NomeDestino VARCHAR(10) NOT NULL,
Descricao VARCHAR(10),
Preco VARCHAR(10)
);

CREATE TABLE Viagem (
Destino VARCHAR(10),
Preço VARCHAR(10),
IDViagem VARCHAR(10) PRIMARY KEY,
DataDeRetorno DATETIME(6),
DataDePartida DATETIME(6)
);

CREATE TABLE CompraViagem (
IDCompra VARCHAR(10) PRIMARY KEY,
DataCompra VARCHAR(10),
PrecoPago VARCHAR(10),
IDCliente VARCHAR(10)
);


ALTER TABLE CompraViagem ADD FOREIGN KEY(IDCliente) REFERENCES Cliente (IDCliente);



